title: Ivy Nguyen
author: Ivy Nguyen
description: Hi there! I am currently a student at the University of Pennsylvania studying Computer Information Systems (CS) graduating May 2024. 
I am looking to hone my skills and knowledge in the tech industry, specifically gearing towards technical documentation. 
I aim to faciliate active, open communication about software processes to both end users and developers, growing as a technical writer.
Thank you for visiting my page!
url: ivyng.dev

plugins:
  - jekyll-feed

theme_config:
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_projects: true # show projects as cards, add in _data/home.yml
  # options for "home" page
  show_education: true
  show_courses: true
  home:
    title_projects: Portfolio
    title_education: Education
    title_college: University of Pennsylvania
    title_dates: August 2020 - May 2024
    title_location: Philadelphia, PA
    title_major: B.A.S. in Computer Information Systems
    title_minor: Minor in Psychology
    title_school: School of Engineering & Applied Science
    title_gpa: 3.56 / 4.00
    title_courses: Relevant Coursework
  



